version: "3"
services:
  springboot:
    image: clement2112/springbootdemo
    build: ./demo
    ports: 
      - 8081:8080
    depends_on:
      - db
      - mockserver
      - redis
    stdin_open: true
    tty: true
    volumes:
      - springbootlogs:/var/logs

  db:
    image: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    expose:
      - 3306
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: '1qa2ws'

  mockserver:
    image: clement2112/mockserver
    build: ./mockserver
    expose:
      - 1080
    ports:
      - 1090:1080
    environment:
       MOCKSERVER_WATCH_INITIALIZATION_JSON: 'true'
       MOCKSERVER_INITIALIZATION_JSON_PATH: '/config/initializerJson.json'
  
  redisinsight:
    image: redislabs/redisinsight
    ports: 
      - 5540:5540
    depends_on:
      - redis
    volumes:
      - redisinsight:/data

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    expose:
      - 6379
volumes:
  mysql_data :
  redisinsight:
  redis_data:
  springBootLogs: