version: "3"
services:
  springboot:
    image: springbootdemo
    build: ./demo
    ports: 
      - 8081:8080
    depends_on:
      - db
      - mockserver
    stdin_open: true
    tty: true
    volumes:
      - /mnt/d/logs:/var/logs

  db:
    image: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    expose:
      - 3306
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: '1qa2ws'

  mockserver:
    image: mockserver/mockserver
    build: ./mockserver
    expose:
      - 1080
    ports:
      - 1090:1080
    environment:
       MOCKSERVER_WATCH_INITIALIZATION_JSON: 'true'
       MOCKSERVER_INITIALIZATION_JSON_PATH: '/config/initializerJson.json'
volumes:
  mysql_data :